#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
desktop_dir="$(cd "$script_dir/.." && pwd)"
repo_root="$(cd "$desktop_dir/.." && pwd)"
backend_dir="$repo_root/backend"
build_root="$desktop_dir/build"
dist_dir="$build_root/backend"
work_dir="$build_root/pyinstaller-work"
spec_dir="$build_root/pyinstaller-spec"
sanitized_env_path="$build_root/.env"
python_cmd="${PYTHON:-python3}"

if [ "$(uname -s)" != "Darwin" ]; then
  echo "This script must be run on macOS because PyInstaller builds native binaries."
  exit 1
fi

if [ "$(uname -m)" != "arm64" ]; then
  echo "This script is configured for Apple Silicon. Run it in a native arm64 terminal on your M-series Mac."
  echo "If Terminal is running through Rosetta, disable Rosetta and try again."
  exit 1
fi

rm -rf "$dist_dir" "$work_dir" "$spec_dir"
mkdir -p "$dist_dir" "$work_dir" "$spec_dir" "$build_root"

is_allowed_env_key() {
  case "$1" in
    ANY_MODEL_ENDPOINT|DEEPSEEK_BASE_URL|ERNIE_BASE_URL|LOCAL_EMBEDDING_MODEL_DIR|LOCAL_EMBEDDING_MAX_LENGTH|EMBEDDING_BASE_URL|EMBEDDING_MODEL|EMBEDDING_DIMENSIONS|EMBEDDING_BATCH_SIZE)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

write_sanitized_env() {
  source_path="$1"
  output_path="$2"
  tmp_path="${output_path}.tmp"

  {
    echo "# Auto-generated by desktop/scripts/build-backend-macos.sh"
    echo "# Sensitive keys are intentionally excluded from packaged builds."
    echo
    echo "DEEPSEEK_BASE_URL=https://api.deepseek.com/v1"
    echo "ERNIE_BASE_URL=https://aistudio.baidu.com/llm/lmapi/v3"
  } > "$tmp_path"

  if [ -f "$source_path" ]; then
    while IFS= read -r line || [ -n "$line" ]; do
      case "$line" in
        ""|\#*) continue ;;
      esac

      key="${line%%=*}"
      value="${line#*=}"
      key="$(printf '%s' "$key" | xargs)"
      if [ -z "$key" ] || [ "$key" = "$line" ]; then
        continue
      fi

      if is_allowed_env_key "$key"; then
        grep -v "^${key}=" "$tmp_path" > "${tmp_path}.next"
        mv "${tmp_path}.next" "$tmp_path"
        printf '%s=%s\n' "$key" "$value" >> "$tmp_path"
      fi
    done < "$source_path"
  fi

  mv "$tmp_path" "$output_path"
}

if [ "${PROVIEW_SKIP_PIP_INSTALL:-0}" != "1" ]; then
  "$python_cmd" -m pip install -r "$backend_dir/requirements.txt" pyinstaller
fi

if ! "$python_cmd" -c "import PyInstaller" >/dev/null 2>&1; then
  "$python_cmd" -m pip install pyinstaller
fi

PLAYWRIGHT_BROWSERS_PATH=0 "$python_cmd" -m playwright install chromium

write_sanitized_env "$backend_dir/.env" "$sanitized_env_path"

"$python_cmd" -m PyInstaller \
  --noconfirm \
  --clean \
  --onedir \
  --name proview-backend \
  --distpath "$dist_dir" \
  --workpath "$work_dir" \
  --specpath "$spec_dir" \
  --paths "$backend_dir" \
  --add-data "$backend_dir/templates:templates" \
  --add-data "$backend_dir/static:static" \
  --add-data "$backend_dir/data:data" \
  --hidden-import openpyxl \
  --hidden-import dotenv \
  --copy-metadata openai \
  --copy-metadata langchain \
  --copy-metadata langchain-core \
  --copy-metadata langchain-community \
  --copy-metadata langchain-openai \
  --copy-metadata playwright \
  --collect-submodules langchain \
  --collect-submodules langchain_core \
  --collect-submodules langchain_community \
  --collect-submodules langchain_openai \
  --collect-submodules openai \
  --collect-submodules cv2 \
  --collect-all openpyxl \
  --collect-all playwright \
  --collect-all numpy \
  --collect-all tokenizers \
  --collect-all PIL \
  --collect-all pillow_heif \
  --collect-all fitz \
  --collect-all docx \
  --collect-all jinja2 \
  --collect-all markdown \
  --add-data "$sanitized_env_path:." \
  "$backend_dir/app.py"

chmod +x "$dist_dir/proview-backend/proview-backend"
