$ErrorActionPreference = 'Stop'

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$desktopDir = (Resolve-Path (Join-Path $scriptDir '..')).Path
$repoRoot = (Resolve-Path (Join-Path $desktopDir '..')).Path
$backendDir = Join-Path $repoRoot 'backend'
$buildRoot = Join-Path $desktopDir 'build'
$distDir = Join-Path $buildRoot 'backend'
$workDir = Join-Path $buildRoot 'pyinstaller-work'
$specDir = Join-Path $buildRoot 'pyinstaller-spec'
$sanitizedEnvPath = Join-Path $buildRoot '.env'

foreach ($dir in @($distDir, $workDir, $specDir)) {
    if (Test-Path $dir) {
        Remove-Item -LiteralPath $dir -Recurse -Force
    }
    New-Item -ItemType Directory -Path $dir | Out-Null
}

$allowedEnvKeys = @(
    'ANY_MODEL_ENDPOINT',
    'DEEPSEEK_BASE_URL',
    'ERNIE_BASE_URL',
    'LOCAL_EMBEDDING_MODEL_DIR',
    'LOCAL_EMBEDDING_MAX_LENGTH',
    'EMBEDDING_BASE_URL',
    'EMBEDDING_MODEL',
    'EMBEDDING_DIMENSIONS',
    'EMBEDDING_BATCH_SIZE'
)

$defaultEnvValues = [ordered]@{
    DEEPSEEK_BASE_URL = 'https://api.deepseek.com/v1'
    ERNIE_BASE_URL = 'https://aistudio.baidu.com/llm/lmapi/v3'
}

function New-SanitizedRuntimeEnvFile {
    param(
        [string]$SourcePath,
        [string]$OutputPath
    )

    $values = [ordered]@{}
    foreach ($entry in $defaultEnvValues.GetEnumerator()) {
        $values[$entry.Key] = $entry.Value
    }

    if (Test-Path $SourcePath) {
        foreach ($line in Get-Content -LiteralPath $SourcePath) {
            if ($line -match '^\s*#') {
                continue
            }

            $trimmed = $line.Trim()
            if (-not $trimmed) {
                continue
            }

            $separatorIndex = $trimmed.IndexOf('=')
            if ($separatorIndex -lt 1) {
                continue
            }

            $key = $trimmed.Substring(0, $separatorIndex).Trim()
            $value = $trimmed.Substring($separatorIndex + 1).Trim()
            if ($allowedEnvKeys -contains $key) {
                $values[$key] = $value
            }
        }
    }

    $content = [System.Collections.Generic.List[string]]::new()
    $content.Add('# Auto-generated by desktop/scripts/build-backend.ps1')
    $content.Add('# Sensitive keys are intentionally excluded from packaged builds.')
    $content.Add('')

    foreach ($entry in $values.GetEnumerator()) {
        if ([string]::IsNullOrWhiteSpace([string]$entry.Value)) {
            continue
        }
        $content.Add("$($entry.Key)=$($entry.Value)")
    }

    Set-Content -LiteralPath $OutputPath -Value $content -Encoding UTF8
}

$hasPyInstaller = $true
try {
    & python -c "import PyInstaller" 2>$null | Out-Null
    if ($LASTEXITCODE -ne 0) {
        $hasPyInstaller = $false
    }
} catch {
    $hasPyInstaller = $false
}

if (-not $hasPyInstaller) {
    & python -m pip install pyinstaller
    if ($LASTEXITCODE -ne 0) {
        throw 'Failed to install PyInstaller.'
    }
}

$args = @(
    '-m', 'PyInstaller',
    '--noconfirm',
    '--clean',
    '--onedir',
    '--name', 'proview-backend',
    '--distpath', $distDir,
    '--workpath', $workDir,
    '--specpath', $specDir,
    '--paths', $backendDir,
    '--add-data', "$backendDir\templates;templates",
    '--add-data', "$backendDir\static;static",
    '--add-data', "$backendDir\data;data",
    '--hidden-import', 'openpyxl',
    '--hidden-import', 'dotenv',
    '--copy-metadata', 'openai',
    '--copy-metadata', 'langchain',
    '--copy-metadata', 'langchain-core',
    '--copy-metadata', 'langchain-community',
    '--copy-metadata', 'langchain-openai',
    '--copy-metadata', 'playwright',
    '--collect-submodules', 'langchain',
    '--collect-submodules', 'langchain_core',
    '--collect-submodules', 'langchain_community',
    '--collect-submodules', 'langchain_openai',
    '--collect-submodules', 'openai',
    '--collect-submodules', 'cv2',
    '--collect-all', 'openpyxl',
    '--collect-all', 'playwright',
    '--collect-all', 'numpy',
    '--collect-all', 'tokenizers',
    '--collect-all', 'PIL',
    '--collect-all', 'pillow_heif',
    '--collect-all', 'fitz',
    '--collect-all', 'docx',
    '--collect-all', 'jinja2',
    '--collect-all', 'markdown',
    (Join-Path $backendDir 'app.py')
)

$envFile = Join-Path $backendDir '.env'
New-SanitizedRuntimeEnvFile -SourcePath $envFile -OutputPath $sanitizedEnvPath
$args += @('--add-data', "$sanitizedEnvPath;.")

& python @args
if ($LASTEXITCODE -ne 0) {
    throw 'Backend packaging failed.'
}
